sudo: false

language: go

dist: bionic

go:
  - 1.12.7

go_import_path: github.com/mdblp/shoreline

env:
  # Using Go module (go 1.12 need this variable to be set to enable modules)
  - GO111MODULE="on"

deploy:
  # Control deployment by setting a value for `on`. Setting the `branch`
  # option to `master` means Travis will only attempt a deployment on
  # builds of your repo's master branch (e.g., after you merge a PR).
  on:
    tags: true
#    branch: dblp
  provider: s3
  # You can refer to environment variables from Travis repo settings!
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  # Name of the S3 bucket to which your site should be uploaded.
  bucket: $AWS_BUCKET
  # Prevent Travis from deleting your built site so it can be uploaded.
  skip_cleanup: true
  # Path of the source directory containing your built site.
  local_dir: deploy
  # Path to a directory containing your built site.
  upload-dir: deploy
  # Set the Cache-Control header.
  cache_control: "max-age=21600"

services:
  - docker
  - mongodb

script:
  - ./build.sh
  - ./test.sh
  - ./artifact.sh
