[[constraint]]
  name = "github.com/tidepool-org/go-common"
  source = "github.com/mdblp/go-common"
  branch = "master"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "v1.0.2"

[prune]
  go-tests = true
  unused-packages = true

