name: Security

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    env:
      GOPRIVATE: github.com/mdblp
    steps:
      - uses: actions/checkout@v4
      - uses: mdblp/.github/.github/actions/setup-go-private@main
        with:
          github-token: ${{ secrets.DBLBOT_PRIVATE_ACCESS_TOKEN }}
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.26
          go-package: ./...
  SBOM:
    uses: mdblp/.github/.github/workflows/sbom.yml@main
    with:
      app-name: shoreline
    secrets: inherit
